import React from 'react';

export default function TermsOfService() {
  const date = new Date().toLocaleDateString();
  const email = "shriramrushikesh@gmail.com";

  return (
    <div className="min-h-screen bg-[#0a0a0c] text-white p-6 md:p-12">
      <div className="max-w-4xl mx-auto prose prose-invert prose-purple">
        <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
        <p className="text-zinc-400 mb-8 font-medium italic">Last Updated: {date}</p>

        <section className="space-y-6">
          <h2 className="text-2xl font-semibold text-purple-400">1. Acceptance of Terms</h2>
          <p>
            By accessing or using LoopLobby, you agree to be bound by these Terms of Service. If you do not agree, you may not use the platform. LoopLobby is provided free of charge and requires no subscription.
          </p>

          <h2 className="text-2xl font-semibold text-purple-400">2. User Conduct</h2>
          <p>
            You agree to use LoopLobby only for lawful purposes. You are prohibited from:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Abusing, harassing, or threatening other users in the chat.</li>
            <li>Attempting to disrupt the synchronization engine or platform stability.</li>
            <li>Uploading or initiating content that violates regional laws.</li>
          </ul>

          <h2 className="text-2xl font-semibold text-purple-400">3. DMCA & Copyright Safe Harbor</h2>
          <div className="p-6 bg-purple-500/10 border border-purple-500/20 rounded-2xl">
            <h3 className="text-lg font-bold mb-2">Notice to Rights Holders</h3>
            <p className="text-sm italic">
              LoopLobby does NOT host, store, or own any music content. All audio and video playback is user-initiated and sourced directly from third-party platforms (like YouTube). LoopLobby serves as a real-time synchronization interface only. We do not exercise editorial control over the content selected by users.
            </p>
          </div>
          <p className="mt-4">
            If you believe your copyright has been infringed, please send a DMCA takedown notice to the third-party platform hosting the content.
          </p>

          <h2 className="text-2xl font-semibold text-purple-400">4. Limitation of Liability</h2>
          <p>
            LoopLobby is provided "as is" without any guarantees or warranties. We are not liable for any technical failures, data loss, or content generated by third-party platforms.
          </p>

          <h2 className="text-2xl font-semibold text-purple-400">5. Governing Law</h2>
          <p>
            These terms are governed by and construed in accordance with the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in India.
          </p>

          <h2 className="text-2xl font-semibold text-purple-400">6. Contact</h2>
          <p>
            For any legal inquiries, please reach out to: <br/>
            <span className="font-bold text-purple-400">{email}</span>
          </p>
        </section>

        <footer className="mt-12 pt-8 border-t border-white/10 text-center text-zinc-500 text-sm">
          &copy; {new Date().getFullYear()} LoopLobby. Play together, vibe together.
        </footer>
      </div>
    </div>
  );
}
